### ISSUE TITLE
Change plotting to take NC variable name not number

### ISSUE THREAD

**Issue by jsadler2** [UW-Hydro/pysumma#2]
I think it makes more sense to use the variable **name** instead of the variable **number** when plotting a variable in the model outputs using the Plotting module.

(e.g., https://github.com/UW-Hydro/pysumma/blob/develop/pysumma/Plotting.py#L19)

**Comment by DavidChoi76** [comment]
updated general plotting code and notebook
[https://github.com/DavidChoi76/pysumma/commit/dd2abde1cbf8e04aa16d0d5dc4b027098cc55062](url)

need to improve layer plot

**Comment by arbennett** [comment]
Done as of 12/14/2018
