### ISSUE TITLE
more informative error msg from Simulation.execute() for incorrect run method

### ISSUE THREAD

**Issue by jsadler2** [UW-Hydro/pysumma#22]
It would be good to have a more informative error statement in the `execute` method of the `Simulation` class if an incorrect `run_method` argument is passed.

**Comment by jsadler2** [comment]
The current msg is: 
```
'No executable defined. Set as "executable" attribute of Simulation or check run_option'
```

**Comment by jsadler2** [comment]
It should list the valid options (e.g., 'local', 'docker-develop', ...)

**Comment by arbennett** [comment]
This has been implemented.
