### ISSUE TITLE
Unable to use BigBuckt option for groundwatr decision

### ISSUE THREAD

**Issue by tusharkh** [UW-Hydro/pysumma#24]
When I try to change the summa groundwater decision to bigBuckt, I encounter an error which suggests that pysumma doesn't recognize this option. Notice the last line of the error message, which lists out valid options that has noXplict listed twice, and bigBuckt not listed.

Running this code:

def run_summa_error(site):
    s = pysumma.Simulation.Simulation(fman_dict[site])
    s.decision_obj.groundwatr.value = 'bigBuckt'
    s.executable = '/opt/local/bin/summa.exe'
    s.library_path = '/opt/local/lib:/opt/local/lib64:$LD_LIBRARY_PATH'
    additional_args = ['export OMP_NUM_THREADS=8']
    return s.execute('test_simpleResistance', 'local', additional_args)

I get:

ValueError                                Traceback (most recent call last)
<ipython-input-64-a2a4f8b1cc53> in <module>()
----> 1 run_summa_error('Amplero')

<ipython-input-63-d9d231f68348> in run_summa_error(site)
      1 def run_summa_error(site):
      2     s = pysumma.Simulation.Simulation(fman_dict[site])
----> 3     s.decision_obj.groundwatr.value = 'bigBuckt'
      4     s.executable = '/opt/local/bin/summa.exe'
      5     s.library_path = '/opt/local/lib:/opt/local/lib64:$LD_LIBRARY_PATH'

/pool0/data/tushark/pysumma/pysumma/Decisions.py in value(self, new_value)
     77             self.write_value(self.value, new_value)
     78         else:
---> 79             raise ValueError('Your input value {} is not one of the valid options {}'.format(new_value, self.options))
     80 
     81 

ValueError: Your input value bigBuckt is not one of the valid options ['qTopmodl', 'noXplict', 'noXplict']

**Comment by DavidChoi76** [comment]
@tusharkh I'm sorry that it's too late. When you look at your Decision text file that you assigned to run summa, you can check the option that is (11) choice of groundwater parameterization. In my decision file, there are three options that are 'qTopmodl', 'bigBuckt', 'noXplict'. To assign bigBuckt method, you have to change 'noXplict' to 'bigBuckt' in Decision text file (84~87 lines). Additionally, you have to check that when you use bigBuckt method, you also have to use "singleBasin" method at (28) choice of method for the spatial representation of groundwater. If you check source code(mDecisions.f90) in source code folder(build-source-engine), you can check the consistency among option from 573 line.
