### ISSUE TITLE
How to Migrate from Python 3.6 to Python 2.7 or multiple use for both version

### ISSUE THREAD

**Issue by DavidChoi76** [UW-Hydro/pysumma#29]

**Comment by jhamman** [comment]
Since pysumma is just starting its development, I would strongly advise NOT supporting Python 2 at all. Pysumma dependencies such as Pandas and Xarray are dropping Python 2 support later this year so any advantage you get from supporting both will be short lived.

**Comment by DavidChoi76** [comment]
@jhamman Thank you for your opinion.
