### ISSUE TITLE
Create parent Option class

### ISSUE THREAD

**Issue by jsadler2** [UW-Hydro/pysumma#3]
Much of the functionality in the `DecisionOption` class methods is also needed for the `SimulationOption` class. It would be nicer to have an abstract `Option` class that the two more specific classes can inherit from.

**Comment by arbennett** [comment]
This has been accomplished by creating 2 parent classes `OptionContainer` and `BaseOption`. The `OptionContainer` refers to a whole set of options, as concretely implemented in the `Decisions` class or the `OutputControl` class. `BaseOption` refers to a single option within one of those files.
