### ISSUE TITLE
Add read/write functionality for "Model_Output" file

### ISSUE THREAD

**Issue by jsadler2** [UW-Hydro/pysumma#4]
Users should be able to read and write the variable terms in the Model_Output file.

**Comment by jsadler2** [comment]
Not sure if this needs to be its own class like the `Decision` class and `Simulation` class.

**Comment by jsadler2** [comment]
Here is an example of what the Model_Output.txt file looks like:
> ! ---------
! model variables
! ---------
nSnow                     | 1  
nSoil                     | 1  
pptrate                   | 1    
airtemp                   | 1    
scalarRainPlusMelt        | 1  
scalarSWE                 | 1   
scalarThroughfallSnow     | 1    
scalarThroughfallRain     | 1    
scalarSnowSublimation     | 1   
scalarInfiltration        | 1    
scalarExfiltration        | 1   
scalarSurfaceRunoff       | 1    
scalarSurfaceTemp         | 1  
scalarSenHeatTotal        | 1 
scalarLatHeatTotal        | 1   
iLayerHeight              | 1   
iLayerLiqFluxSoil         | 1   
mLayerTemp                | 1   
mLayerDepth               | 1    
mLayerLiqFluxSoil         | 1    
mLayerVolFracIce          | 1    
mLayerVolFracLiq          | 1    
mLayerVolFracWat          | 1    
mLayerMatricHead          | 1    
basin__SurfaceRunoff      | 1
basin__ColumnOutflow      | 1
basin__AquiferStorage     | 1
basin__AquiferRecharge    | 1
basin__AquiferBaseflow    | 1
basin__AquiferTranspire   | 1
averageInstantRunoff      | 1
averageRoutedRunoff       | 1

**Comment by jsadler2** [comment]
The location of this file is the `setting_path` + `OUTPUT_CONTROL` in the fileManager.txt file.

**Comment by arbennett** [comment]
There is now an `OutputControl` class which handles this functionality. It is internally accessed on a simulation object as `simulation.output_control`. It follows the same API as the other `OptionContainer` classes which have `get_value`, `set_value`, and other functionality.
