### ISSUE TITLE
e.start() problem to execute ensemble simulation

### ISSUE THREAD

**Issue by DavidChoi76** [UW-Hydro/pysumma#69]
Even though e.start() command finished in Jupyter Notebook, the output of summa is continuously generating. So we have to wait for this process finishing. Without waiting, when we try to combine output dataset from NetCDF, that makes errors.

**Comment by arbennett** [comment]
The preferred method to run both simulations and ensembles is to use their `run` methods. The `start` methods allow for a bit more control, so just launch the processes in the background. This may be useful if users don't want to halt execution of other tasks.
