### ISSUE TITLE
Add ability to download NLDAS forcing data

### ISSUE THREAD

**Issue by DavidChoi76** [UW-Hydro/pysumma#91]

**Comment by arbennett** [comment]
I don't think this falls into the scope of pysumma. You might create your own project/repo/package for this.

**Comment by DavidChoi76** [comment]
I know we can use MetSim you created to create forcing data. But this is an alternative way to get forcing data from online. Is there any good approach to create forcing data except MetSim?

**Comment by arbennett** [comment]
There are other ways to generate forcing data. Reanalysis products like ERA are one, along with purely observed datasets such as Fluxnet and Snotel. But generating/downloading those datasets are a separate task and also don't fall within the scope of pysumma (much as MetSim doesn't).

**Comment by DavidChoi76** [comment]
Okay, I understood that. If I think it is necessary to download and generate forcing data, I will create an individual repo and if it is useful for SUMMA simulation, we can mention and use it in pysumma tutorial notebooks.
